### ISSUE TITLE
/randomtm don't work in 8.2

### ISSUE THREAD

**Issue by PGGreed** [xPXpanD/EvenMorePixelmonCommands#2]
**Describe the bug**
When doing /randomtm there's an error.

**To Reproduce**
1. Do /randomtm

![](https://i.gyazo.com/6d4f580fe1df373121b66c1ca2689c13.png)

**Expected behavior**

**Screenshots**

**Versions**
 - Even More Pixelmon Commands version: [5.1.3]
 - Pixelmon version: [ Reforged 8.2]
 - Forge version: [e.g. 2768]
 - SpongeForge version: [e.g. 3514]

**Additional context**

**Comment by xPXpanD** [comment]
Closing this issue (and the project in general) due to me recently having been booted off of the Pixelmon mod team over a minor disagreement, if you can even call it that. Guess that's what 5.5 years on the team gets you... The code's still public and the license is permissive if people want to keep working on it, but I am unable to continue working on these projects myself. Sorry for the bad news.
